In [59]:
import pypsa
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import geopandas as gpd
from pypsa.plot import add_legend_lines, add_legend_patches, add_legend_semicircles
import yaml

**Set Up**

In [60]:
fn = 'resources/DK_test/networks/base_s_2__12h_2050.nc'
fn_new = 'resources/DK_test/networks/base_s_2__12h_2050.nc'

In [61]:
n = pypsa.Network(fn)

n_pre_cluster = pypsa.Network(fn)

WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.0.4 available! (Current: 0.35.2)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, global_constraints, links, loads, stores
WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.0.4 available! (Current: 0.35.2)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, global_constraints, links, loads, stores

**Options**

In [62]:
ongrid=False
cluster_cost_reduction=0.99

**CF Computation for Resource Classes**

In [63]:
cf_onshorewind=n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.astype(str).str.contains('onwind')].mean().sort_values(ascending=False)
cf_solar=n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.astype(str).str.contains('solar')].mean().sort_values(ascending=False)

**Buses, Links and Generators of the Cluster Addition**

In [64]:
n.add("Bus",
      name="DK0 cluster",
      v_nom=n_pre_cluster.buses.at["DK0 0", "v_nom"],
      x=n_pre_cluster.buses.at["DK0 0", "x"],
      y=n_pre_cluster.buses.at["DK0 0", "y"],
      unit=n_pre_cluster.buses.at["DK0 0", "unit"],
      location=n_pre_cluster.buses.at["DK0 0", "location"],
      country="DK",
      carrier='AC',
      control=n_pre_cluster.buses.at["DK0 0", "control"],
      substation_lv=n_pre_cluster.buses.at["DK0 0", "substation_lv"],
      substation_off=n_pre_cluster.buses.at["DK0 0", "substation_off"],
      )

n.add("Bus",
      name="DK0 cluster H2",
      country="DK",
      x=n_pre_cluster.buses.at["DK0 0", "x"],
      y=n_pre_cluster.buses.at["DK0 0", "y"],
      location=n_pre_cluster.buses.at["DK0 0", "location"],
      unit=n_pre_cluster.buses.at["DK0 0 H2", "unit"],
      carrier='H2')

Index(['DK0 cluster H2'], dtype='object')

In [ ]:
n.add(
        "Link",
        name="DK0 cluster H2 Electrolysis",
        bus0="DK0 cluster",
        bus1="DK0 cluster H2",
        p_nom_extendable=True,
        carrier="H2 Electrolysis",
        efficiency=n_pre_cluster.links.at["DK0 0 H2 Electrolysis", "efficiency"],
        capital_cost=n_pre_cluster.links.at["DK0 0 H2 Electrolysis", "capital_cost"]*(1-cluster_cost_reduction),
        marginal_cost=n_pre_cluster.links.at["DK0 0 H2 Electrolysis", "marginal_cost"]*(1-cluster_cost_reduction),
        lifetime=n_pre_cluster.links.at["DK0 0 H2 Electrolysis", "lifetime"],
        reversed=False,
        overwrite=True,
    )

n.add(
        "Link",
        name="DK0 cluster methanolization",
        bus0="DK0 cluster H2",
        bus1=n.links.at["DK0 0 methanolisation", "bus1"],
        bus2="DK0 cluster",
        bus3=n.links.at["DK0 0 methanolisation", "bus3"],
        bus4=n.links.at["DK0 0 methanolisation", "bus4"],
        carrier="methanolisation",
        p_nom_extendable=True,
        p_min_pu=n.links.at["DK0 0 methanolisation", "p_min_pu"],
        capital_cost=n.links.at["DK0 0 methanolisation", "capital_cost"]*(1-cluster_cost_reduction),
        marginal_cost=n.links.at["DK0 0 methanolisation", "marginal_cost"]*(1-cluster_cost_reduction),
        lifetime=n.links.at["DK0 0 methanolisation", "lifetime"],
        efficiency=n.links.at["DK0 0 methanolisation", "efficiency"],
        efficiency2=n.links.at["DK0 0 methanolisation", "efficiency2"],
        efficiency3=n.links.at["DK0 0 methanolisation", "efficiency3"],
        efficiency4=n.links.at["DK0 0 methanolisation", "efficiency4"],
        reversed=False,
        overwrite=True,
    )

n.add("Store",
      name="DK0 cluster H2 Store",
      bus="DK0 cluster H2",
      carrier="H2 Store",
      e_nom_extendable=True,
      capital_cost=n.stores.at["DK0 0 H2 Store", "capital_cost"]*(1-cluster_cost_reduction),
      marginal_cost=n.stores.at["DK0 0 H2 Store", "marginal_cost"]*(1-cluster_cost_reduction),
      e_initial_per_period=n.stores.at["DK0 0 H2 Store", "e_initial_per_period"],
      e_cyclic=n.stores.at["DK0 0 H2 Store", "e_cyclic"],
      e_cyclic_per_period=n.stores.at["DK0 0 H2 Store", "e_cyclic_per_period"],
      )


if ongrid==True :
    
    n.add(
        "Link",
        name="DK0 cluster electricity",
        bus0="DK0 cluster",
        bus1="DK0 0",
        carrier="AC",   
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=False,
        overwrite=True,
    )
    n.add(
        "Link",
        name="DK0 cluster electricity back",
        bus0="DK0 0",
        bus1="DK0 cluster",
        carrier="AC",
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=True,
        overwrite=True,
    )

else:
    if "DK0 cluster electricity" in n.links.index:
        n.remove(
            "Link",
            name="DK0 cluster electricity",
        )
    if "DK0 cluster electricity back" in n.links.index:
        n.remove(
            "Link",
            name="DK0 cluster electricity back",
        )



n.add(
        "Generator",
        name="DK0 0 cluster 4 onwind",
        bus="DK0 cluster",
        carrier="onwind",
        p_nom_max=n.generators.at["DK0 0 4 onwind", "p_nom_max"],
        p_max_pu=n.generators.at["DK0 0 4 onwind", "p_max_pu"],
        marginal_cost=n.generators.at["DK0 0 4 onwind", "marginal_cost"]*(1-cluster_cost_reduction),
        capital_cost=n.generators.at["DK0 0 4 onwind", "capital_cost"]*(1-cluster_cost_reduction),
        efficiency=n.generators.at["DK0 0 4 onwind", "efficiency"],
        p_nom_extendable=True,
        overwrite=True,)

Index(['DK0 0 cluster 4 onwind'], dtype='object')

In [66]:
n.links.loc[n.links.index.str.contains("Electrolysis")]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 H2 Electrolysis,DK0 0,DK0 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 H2 Electrolysis,DK1 0,DK1 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster H2 Electrolysis,DK0 cluster,DK0 cluster H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [67]:
n.generators_t['p_max_pu']['DK0 0 cluster 4 onwind'] = n_pre_cluster.generators_t['p_max_pu']['DK0 0 4 onwind']

n.remove(
        "Generator",
        name="DK0 0 4 onwind",
)

In [68]:
n_pre_cluster.generators.loc[ 'DK0 0 4 onwind',:]

bus                                DK0 0
control                               PQ
type
p_nom                         145.033227
p_nom_mod                            0.0
p_nom_extendable                    True
p_nom_min                     145.033227
p_nom_max                    1229.646254
p_min_pu                             0.0
p_max_pu                             1.0
p_set                                0.0
e_sum_min                           -inf
e_sum_max                            inf
q_set                                0.0
sign                                 1.0
carrier                           onwind
marginal_cost                      0.015
marginal_cost_quadratic              0.0
active                              True
build_year                             0
lifetime                            30.0
capital_cost               108204.668804
efficiency                           1.0
committable                        False
start_up_cost                        0.0
shut_down_cost                       0.0
stand_by_cost                        0.0
min_up_time                            0
min_down_time                          0
up_time_before                         1
down_time_before                       0
ramp_limit_up                        NaN
ramp_limit_down                      NaN
ramp_limit_start_up                  1.0
ramp_limit_shut_down                 1.0
weight                               1.0
p_nom_opt                            0.0
location
unit
Name: DK0 0 4 onwind, dtype: object

In [69]:
n.links["reversed"] = n.links["reversed"].fillna(False).astype(bool)

**Printing to Check**

In [70]:
n.links.loc[n.links["carrier"]=='methanolisation']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 methanolisation,DK0 0 H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 methanolisation,DK1 0 H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster methanolization,DK0 cluster H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [71]:
n.links.loc[n.links["carrier"].str.contains('H2 Electrolysis')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 H2 Electrolysis,DK0 0,DK0 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 H2 Electrolysis,DK1 0,DK1 0 H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster H2 Electrolysis,DK0 cluster,DK0 cluster H2,,H2 Electrolysis,0.6994,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [72]:
n.buses

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network,country,substation_lv,substation_off
Bus,,,,,,,,,,,,,,,,
DK0 0,380.0,,9.648393,55.893047,AC,MWh_el,DK0 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
DK1 0,380.0,,12.303316,55.515974,AC,MWh_el,DK1 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
EU,1.0,,-5.500000,46.000000,none,,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
co2 atmosphere,1.0,,-5.500000,46.000000,co2,t_co2,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 co2 stored,1.0,,9.648393,55.893047,co2 stored,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 co2 stored,1.0,,12.303316,55.515974,co2 stored,t_co2,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 co2 sequestered,1.0,,9.648393,55.893047,co2 sequestered,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 co2 sequestered,1.0,,12.303316,55.515974,co2 sequestered,t_co2,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 gas,1.0,,9.648393,55.893047,gas,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 gas,1.0,,12.303316,55.515974,gas,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 H2,1.0,,9.648393,55.893047,H2,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 H2,1.0,,12.303316,55.515974,H2,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 battery,1.0,,9.648393,55.893047,battery,MWh_el,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 battery,1.0,,12.303316,55.515974,battery,MWh_el,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 EV battery,1.0,,9.648393,55.893047,EV battery,MWh_el,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 EV battery,1.0,,12.303316,55.515974,EV battery,MWh_el,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 urban central heat,1.0,,9.648393,55.893047,urban central heat,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 urban central heat,1.0,,12.303316,55.515974,urban central heat,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 urban central water tanks,1.0,,9.648393,55.893047,urban central water tanks,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 urban central water tanks,1.0,,12.303316,55.515974,urban central water tanks,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 urban central water pits,1.0,,9.648393,55.893047,urban central water pits,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 urban central water pits,1.0,,12.303316,55.515974,urban central water pits,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 biogas,1.0,,9.648393,55.893047,biogas,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 biogas,1.0,,12.303316,55.515974,biogas,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 solid biomass,1.0,,9.648393,55.893047,solid biomass,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 solid biomass,1.0,,12.303316,55.515974,solid biomass,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
EU oil,1.0,,-5.500000,46.000000,oil,MWh_th,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
EU oil primary,1.0,,-5.500000,46.000000,oil primary,MWh_th,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
EU NH3,1.0,,-5.500000,46.000000,NH3,,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
EU methanol,1.0,,-5.500000,46.000000,methanol,MWh_th,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 solid biomass for industry,1.0,,9.648393,55.893047,solid biomass for industry,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 solid biomass for industry,1.0,,12.303316,55.515974,solid biomass for industry,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 gas for industry,1.0,,9.648393,55.893047,gas for industry,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 gas for industry,1.0,,12.303316,55.515974,gas for industry,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
EU industry methanol,1.0,,-5.500000,46.000000,industry methanol,MWh_LHV,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 naphtha for industry,1.0,,9.648393,55.893047,naphtha for industry,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 naphtha for industry,1.0,,12.303316,55.515974,naphtha for industry,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 non-sequestered HVC,1.0,,9.648393,55.893047,non-sequestered HVC,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 non-sequestered HVC,1.0,,12.303316,55.515974,non-sequestered HVC,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 process emissions,1.0,,9.648393,55.893047,process emissions,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 process emissions,1.0,,12.303316,55.515974,process emissions,t_co2,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
EU shipping methanol,1.0,,-5.500000,46.000000,shipping methanol,MWh_LHV,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 kerosene for aviation,1.0,,9.648393,55.893047,kerosene for aviation,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 kerosene for aviation,1.0,,12.303316,55.515974,kerosene for aviation,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 agriculture machinery oil,1.0,,9.648393,55.893047,agriculture machinery oil,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 agriculture machinery oil,1.0,,12.303316,55.515974,agriculture machinery oil,MWh_LHV,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 low voltage,1.0,,9.648393,55.893047,low voltage,MWh_el,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 low voltage,1.0,,12.303316,55.515974,low voltage,MWh_el,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 home battery,1.0,,9.648393,55.893047,home battery,MWh_el,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 home battery,1.0,,12.303316,55.515974,home battery,MWh_el,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 rural heat,1.0,,9.648393,55.893047,rural heat,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 rural water tanks,1.0,,9.648393,55.893047,rural water tanks,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 urban decentral heat,1.0,,9.648393,55.893047,urban decentral heat,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 0 urban decentral water tanks,1.0,,9.648393,55.893047,urban decentral water tanks,MWh_th,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 rural heat,1.0,,12.303316,55.515974,rural heat,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 rural water tanks,1.0,,12.303316,55.515974,rural water tanks,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 urban decentral heat,1.0,,12.303316,55.515974,urban decentral heat,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK1 0 urban decentral water tanks,1.0,,12.303316,55.515974,urban decentral water tanks,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 cluster,380.0,,9.648393,55.893047,AC,MWh_el,DK0 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
DK0 cluster H2,1.0,,9.648393,55.893047,H2,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN

In [73]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,location,unit
Generator,,,,,,,,,,,,,,,,,,,,,
DK0 0 0 offwind-ac,DK0 0,PQ,,1.602600e+03,0.0,True,1602.600000,1.460238e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-ac,DK1 0,PQ,,1.050000e+03,0.0,True,1050.000000,9.543253e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 offwind-float,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,6.037907e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-float,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,3.241909e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar,DK0 0,PQ,,8.002000e+02,0.0,True,800.200000,3.208917e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 solar,DK0 0,PQ,,4.740000e+02,0.0,True,474.000000,4.430542e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 solar,DK0 0,PQ,,2.830000e+02,0.0,True,283.000000,3.151701e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 solar,DK0 0,PQ,,7.350000e+01,0.0,True,73.500000,1.364164e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 4 solar,DK0 0,PQ,,7.000000e+00,0.0,True,7.000000,1.659310e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,4.705808e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 solar,DK1 0,PQ,,1.700000e+02,0.0,True,170.000000,1.841362e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 solar,DK1 0,PQ,,3.540000e+02,0.0,True,354.000000,1.133834e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 solar,DK1 0,PQ,,1.500000e+01,0.0,True,15.000000,2.552206e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 solar,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,9.716842e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 offwind-dc,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,3.051995e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-dc,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,9.783270e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 onwind,DK0 0,PQ,,1.112003e+03,0.0,True,1112.003168,2.885105e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 onwind,DK0 0,PQ,,1.383553e+03,0.0,True,1383.553340,2.095206e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 onwind,DK0 0,PQ,,5.659556e+02,0.0,True,565.955595,7.662129e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 onwind,DK0 0,PQ,,5.978417e+02,0.0,True,597.841651,5.834156e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 onwind,DK1 0,PQ,,1.044400e+02,0.0,True,104.439954,3.679788e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 onwind,DK1 0,PQ,,1.079376e+02,0.0,True,107.937576,2.538478e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 onwind,DK1 0,PQ,,1.375523e+02,0.0,True,137.552329,4.037588e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 onwind,DK1 0,PQ,,2.336286e+02,0.0,True,233.628561,3.824337e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 onwind,DK1 0,PQ,,1.696916e+02,0.0,True,169.691598,1.955588e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar-hsat,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,1.057286e+05,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar-hsat,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,3.299191e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 gas,DK0 0 gas,PQ,,7.803446e+03,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 gas,DK1 0 gas,PQ,,3.379370e+03,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 urban central heat vent,DK0 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK1 0 urban central heat vent,DK1 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK0 0 urban central solar thermal collector,DK0 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 urban central solar thermal collector,DK1 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 biogas,DK0 0 biogas,PQ,,9.364836e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 biogas,DK1 0 biogas,PQ,,2.623672e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 solid biomass,DK0 0 solid biomass,PQ,,9.668602e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 solid biomass,DK1 0 solid biomass,PQ,,2.528983e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 solid biomass transported,DK0 0 solid biomass,PQ,,1.000000e+04,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 solid biomass transported,DK1 0 solid biomass,PQ,,1.000000e+04,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
EU oil primary,EU oil primary,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.430564e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.801204e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.355563e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,4.278514e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 4 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,2.293480e+00,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,6.137931e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.947568e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,3.958204e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,3.186837e+01,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,9.587147e+00,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 rural heat vent,DK0 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK0 0 rural solar thermal collector,DK0 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 urban decentral heat vent,DK0 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK0 0 urban decentral solar thermal collector,DK0 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 rural heat vent,DK1 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK1 0 rural solar thermal collector,DK1 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 urban decentral heat vent,DK1 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK1 0 urban decentral solar thermal collector,DK1 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 cluster 4 onwind,DK0 cluster,PQ,,0.000000e+00,0.0,True,0.000000,1.229646e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,NaN,NaN

In [74]:
n.links.loc[n.links["carrier"]=='DC']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
relation/5487095-400-DC,DK0 0,DK1 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,False,171.53249
relation/5487095-400-DC-reversed,DK1 0,DK0 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,True,171.53249

In [75]:
n.stores.loc[n.stores.index.str.contains("H2 Store")]

,bus,type,carrier,e_nom,e_nom_mod,e_nom_extendable,e_nom_min,e_nom_max,e_min_pu,e_max_pu,...,marginal_cost,marginal_cost_quadratic,marginal_cost_storage,capital_cost,standing_loss,active,build_year,lifetime,e_nom_opt,location
Store,,,,,,,,,,,,,,,,,,,,,
DK0 0 H2 Store,DK0 0 H2,,H2 Store,0.0,0.0,True,0.0,2.013398e+08,0.0,1.0,...,0.0,0.0,0.0,89.430064,0.0,True,0,100.0,0.0,
DK1 0 H2 Store,DK1 0 H2,,H2 Store,0.0,0.0,True,0.0,2.879317e+06,0.0,1.0,...,0.0,0.0,0.0,89.430064,0.0,True,0,100.0,0.0,
DK0 cluster H2 Store,DK0 cluster H2,,H2 Store Cluster,0.0,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,0.894301,0.0,True,0,inf,0.0,NaN

**Exporting**

In [76]:
n.export_to_netcdf(fn_new)

INFO:pypsa.network.io:Exported network 'Unnamed Network'saved to 'resources/DK_test/networks/base_s_2__12h_2050.nc contains: links, global_constraints, loads, stores, carriers, generators, buses

<xarray.Dataset> Size: 503kB
Dimensions:                               (snapshots: 730,
                                           investment_periods: 0, links_i: 137,
                                           links_t_efficiency_i: 8,
                                           links_t_p_max_pu_i: 4,
                                           global_constraints_i: 3,
                                           loads_i: 37, loads_t_p_set_i: 10,
                                           stores_i: 29,
                                           stores_t_e_min_pu_i: 2,
                                           stores_t_e_max_pu_i: 4,
                                           carriers_i: 118, generators_i: 59,
                                           generators_t_p_max_pu_i: 44,
                                           buses_i: 60)
Coordinates: (12/15)
  * snapshots                             (snapshots) int64 6kB 0 1 ... 728 729
  * investment_periods                    (investment_periods) object 0B
  * links_i                               (links_i) object 1kB 'relation/5487...
  * links_t_efficiency_i                  (links_t_efficiency_i) object 64B '...
  * links_t_p_max_pu_i                    (links_t_p_max_pu_i) object 32B 'DK...
  * global_constraints_i                  (global_constraints_i) object 24B '...
    ...                                    ...
  * stores_t_e_min_pu_i                   (stores_t_e_min_pu_i) object 16B 'D...
  * stores_t_e_max_pu_i                   (stores_t_e_max_pu_i) object 32B 'D...
  * carriers_i                            (carriers_i) object 944B 'AC' ... '...
  * generators_i                          (generators_i) object 472B 'DK0 0 0...
  * generators_t_p_max_pu_i               (generators_t_p_max_pu_i) object 352B ...
  * buses_i                               (buses_i) object 480B 'DK0 0' ... '...
Data variables: (12/90)
    snapshots_snapshot                    (snapshots) datetime64[ns] 6kB 2013...
    snapshots_objective                   (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_stores                      (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_generators                  (snapshots) float64 6kB 12.0 ... 12.0
    investment_periods_objective          (investment_periods) float64 0B
    investment_periods_years              (investment_periods) float64 0B
    ...                                    ...
    buses_unit                            (buses_i) object 480B 'MWh_el' ... ...
    buses_location                        (buses_i) object 480B 'DK0 0' ... '...
    buses_control                         (buses_i) object 480B 'Slack' ... 'PQ'
    buses_country                         (buses_i) object 480B 'DK' ... 'DK'
    buses_substation_lv                   (buses_i) float64 480B 1.0 1.0 ... nan
    buses_substation_off                  (buses_i) float64 480B 1.0 1.0 ... nan
Attributes:
    network__multi_invest:  0
    network_name:           Unnamed Network
    network_pypsa_version:  0.35.2
    network_srid:           4326
    crs:                    {"_crs": "GEOGCRS[\"WGS 84\",ENSEMBLE[\"World Geo...
    meta:                   {"version": "v2025.07.0", "tutorial": false, "log...

In [77]:
n.links

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
relation/5487095-400-DC,DK0 0,DK1 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,False,171.53249
DK0 0 co2 sequestered,DK0 0 co2 stored,DK0 0 co2 sequestered,,co2 sequestered,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 co2 sequestered,DK1 0 co2 stored,DK1 0 co2 sequestered,,co2 sequestered,1.000000,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 0 OCGT,DK0 0 gas,DK0 0,,OCGT,0.430000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 OCGT,DK1 0 gas,DK1 0,,OCGT,0.430000,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DK1 0 urban decentral resistive heater,DK1 0 low voltage,DK1 0 urban decentral heat,,urban decentral resistive heater,0.900000,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK1 0 urban decentral water tanks charger,DK1 0 urban decentral heat,DK1 0 urban decentral water tanks,,urban decentral water tanks charger,1.000000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,0.15,,False,0.00000
DK1 0 urban decentral water tanks discharger,DK1 0 urban decentral water tanks,DK1 0 urban decentral heat,,urban decentral water tanks discharger,1.000000,True,0,30.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.00000
DK0 cluster H2 Electrolysis,DK0 cluster,DK0 cluster H2,,H2 Electrolysis,0.699400,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
DK0 cluster methanolization,DK0 cluster H2,EU methanol,,methanolisation,0.878700,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN