In [41]:
import pypsa
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import geopandas as gpd
from pypsa.plot import add_legend_lines, add_legend_patches, add_legend_semicircles
import yaml
from pathlib import Path

**Set Up**

In [42]:
fn = 'resources/DK_test/networks/base_s_2__12h_2050.nc'

In [43]:
n= pypsa.Network(fn)

WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:New version 1.0.5 available! (Current: 0.35.2)
INFO:pypsa.network.io:Imported network 'Unnamed Network' has buses, carriers, generators, global_constraints, links, loads, stores

In [44]:
p = Path(fn)  
try:
    if p.exists():
        p.unlink()
        print(f"Deleted {p}")
    else:
        print(f"File not found: {p}")
except Exception as e:
    print(f"Failed to delete {p}: {e}")

Deleted resources/DK_test/networks/base_s_2__12h_2050.nc

**Options**

In [45]:
ongrid=True
cluster_cost_reduction=0.20

**CF Computation for Resource Classes**

In [46]:
cf_onshorewind=n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.astype(str).str.contains('onwind')].mean().sort_values(ascending=False)
cf_solar=n.generators_t['p_max_pu'].loc[:, n.generators_t['p_max_pu'].columns.astype(str).str.contains('solar')].mean().sort_values(ascending=False)

**Buses, Links and Generators of the Cluster Addition**

In [47]:
n.add("Bus",
      name="DK0 cluster",
      v_nom=n.buses.at["DK0 0", "v_nom"],
      x=n.buses.at["DK0 0", "x"],
      y=n.buses.at["DK0 0", "y"],
      unit=n.buses.at["DK0 0", "unit"],
      location=n.buses.at["DK0 0", "location"],
      country="DK",
      carrier='AC',
      control=n.buses.at["DK0 0", "control"],
      substation_lv=n.buses.at["DK0 0", "substation_lv"],
      substation_off=n.buses.at["DK0 0", "substation_off"],
      )

n.add("Bus",
      name="DK0 cluster H2",
      country="DK",
      x=n.buses.at["DK0 0", "x"],
      y=n.buses.at["DK0 0", "y"],
      location=n.buses.at["DK0 0", "location"],
      unit=n.buses.at["DK0 0 H2", "unit"],
      carrier='H2')

n.add("Bus",
      name= "DK0 cluster storage H2",
      country="DK",
      x=n.buses.at["DK0 0", "x"],
      y=n.buses.at["DK0 0", "y"],
      location=n.buses.at["DK0 0", "location"],
      unit=n.buses.at["DK0 0 H2", "unit"],
      carrier='H2 Store')

n.add("Bus",
      name= "DK0 cluster batteries",
      country="DK",
      x=n.buses.at["DK0 0", "x"],
      y=n.buses.at["DK0 0", "y"],
      location=n.buses.at["DK0 0", "location"],
      unit=n.buses.at["DK0 0", "unit"],
      carrier='battery')

Index(['DK0 cluster batteries'], dtype='object')

In [48]:
n.add(
        "Link",
        name="DK0 cluster H2 Electrolysis",
        bus0="DK0 cluster",
        bus1="DK0 cluster H2",
        p_nom_extendable=True,
        carrier="H2 Electrolysis",
        efficiency=n.links.at["DK0 0 H2 Electrolysis", "efficiency"],
        capital_cost=n.links.at["DK0 0 H2 Electrolysis", "capital_cost"]*(1-cluster_cost_reduction),
        marginal_cost=n.links.at["DK0 0 H2 Electrolysis", "marginal_cost"]*(1-cluster_cost_reduction),
        lifetime=n.links.at["DK0 0 H2 Electrolysis", "lifetime"],
        reversed=False,
        overwrite=True,
    )

n.add(
        "Link",
        name="DK0 cluster methanolization",
        bus0="DK0 cluster H2",
        bus1=n.links.at["DK0 0 methanolisation", "bus1"],
        bus2="DK0 cluster",
        bus3=n.links.at["DK0 0 methanolisation", "bus3"],
        bus4=n.links.at["DK0 0 methanolisation", "bus4"],
        carrier=n.links.at["DK0 0 methanolisation", "carrier"],
        p_nom_extendable=True,
        #p_nom_min=1,
        p_min_pu=n.links.at["DK0 0 methanolisation", "p_min_pu"],
        capital_cost=n.links.at["DK0 0 methanolisation", "capital_cost"]*(1-cluster_cost_reduction),
        marginal_cost=n.links.at["DK0 0 methanolisation", "marginal_cost"]*(1-cluster_cost_reduction),
        lifetime=n.links.at["DK0 0 methanolisation", "lifetime"],
        efficiency=n.links.at["DK0 0 methanolisation", "efficiency"],
        efficiency2=n.links.at["DK0 0 methanolisation", "efficiency2"],
        efficiency3=n.links.at["DK0 0 methanolisation", "efficiency3"],
        efficiency4=n.links.at["DK0 0 methanolisation", "efficiency4"],
        reversed=False,
        overwrite=True,
    )


if ongrid==True :
    
    n.add(
        "Link",
        name="DK0 cluster electricity",
        bus0="DK0 cluster",
        bus1="DK0 0",
        carrier="AC",   
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=False,
        overwrite=True,
    )
    n.add(
        "Link",
        name="DK0 cluster electricity back",
        bus0="DK0 0",
        bus1="DK0 cluster",
        carrier="AC",
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=True,
        overwrite=True,
    )

else:
    if "DK0 cluster electricity" in n.links.index:
        n.remove(
            "Link",
            name="DK0 cluster electricity",
        )
    if "DK0 cluster electricity back" in n.links.index:
        n.remove(
            "Link",
            name="DK0 cluster electricity back",
        )

In [49]:
# n.add("Load",
#       name="EU shipping methanol",
#       carrier="shipping methanol",
#       p_set=100,
#       bus="EU shipping methanol",
#       overwrite=True
# )

**Storages**

In [50]:
n.add(
        "Link",
        name="DK0 cluster H2 store",
        bus0="DK0 cluster H2",
        bus1="DK0 cluster storage H2",
        carrier="H2 Charge",   
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=False,
        overwrite=True,
    )
n.add(
        "Link",
        name="DK0 cluster H2 store back",
        bus0="DK0 cluster storage H2",
        bus1="DK0 cluster H2",
        carrier="H2 Discharge",
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=True,
        overwrite=True,
    )

n.add("Store",
      name="DK0 cluster H2 Store",
      bus="DK0 cluster storage H2",
      carrier="H2 Store",
      e_nom_extendable=True,
      capital_cost=n.stores.at["DK0 0 H2 Store", "capital_cost"]*(1-cluster_cost_reduction),
      marginal_cost=n.stores.at["DK0 0 H2 Store", "marginal_cost"]*(1-cluster_cost_reduction),
      e_initial_per_period=n.stores.at["DK0 0 H2 Store", "e_initial_per_period"],
      e_cyclic=n.stores.at["DK0 0 H2 Store", "e_cyclic"],
      e_cyclic_per_period=n.stores.at["DK0 0 H2 Store", "e_cyclic_per_period"],
      overwrite=True,
      )


n.add(
        "Link",
        name="DK0 cluster battery store",
        bus0="DK0 cluster",
        bus1="DK0 cluster batteries",
        carrier="battery Charge",   
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=False,
        overwrite=True,
    )
n.add(
        "Link",
        name="DK0 cluster battery store back",
        bus0="DK0 cluster batteries",
        bus1="DK0 cluster",
        carrier="battery Discharge",
        p_nom_extendable=True,
        efficiency=1.0,
        capital_cost=0.0,
        marginal_cost=0.0,
        reversed=True,
        overwrite=True,
    )

n.add("Store",
      name="DK0 cluster battery Store",
      bus="DK0 cluster batteries",
      carrier="battery",
      e_nom_extendable=True,
      capital_cost=n.stores.at["DK0 0 battery", "capital_cost"]*(1-cluster_cost_reduction),
      marginal_cost=n.stores.at["DK0 0 battery", "marginal_cost"]*(1-cluster_cost_reduction),
      e_initial_per_period=n.stores.at["DK0 0 battery", "e_initial_per_period"],
      e_cyclic=n.stores.at["DK0 0 battery", "e_cyclic"],
      e_cyclic_per_period=n.stores.at["DK0 0 battery", "e_cyclic_per_period"],
      overwrite=True,
      )

Index(['DK0 cluster battery Store'], dtype='object')

In [51]:
n.add(
        "Generator",
        name="DK0 0 cluster 4 onwind",
        bus="DK0 cluster",
        carrier="onwind",
        p_nom_max=n.generators.at["DK0 0 4 onwind", "p_nom_max"],
        p_max_pu=n.generators.at["DK0 0 4 onwind", "p_max_pu"],
        marginal_cost=n.generators.at["DK0 0 4 onwind", "marginal_cost"]*(1-cluster_cost_reduction),
        capital_cost=n.generators.at["DK0 0 4 onwind", "capital_cost"]*(1-cluster_cost_reduction),
        efficiency=n.generators.at["DK0 0 4 onwind", "efficiency"],
        p_nom_extendable=True,
        overwrite=True,)

Index(['DK0 0 cluster 4 onwind'], dtype='object')

In [52]:
n.generators_t['p_max_pu']['DK0 0 cluster 4 onwind'] = n.generators_t['p_max_pu']['DK0 0 4 onwind']

n.remove(
        "Generator",
        name="DK0 0 4 onwind",
)

In [53]:
n.links["reversed"] = n.links["reversed"].fillna(False).astype(bool)

**Global Constraint to try to force methanol**

In [54]:
# n.add("GlobalConstraint",
#        name="methanol_cluster_min",
#        type="operational_limit",
#        carrier_attribute='methanolisation cluster',
#        sense= ">=",
#        constant= n.loads.p_set['EU shipping methanol']*0.1,
#        overwrite=True
# )

#it doesn't work

**Printing to Check**

In [55]:
n.links.loc[n.links["bus1"]=='EU methanol']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 solid biomass biomass-to-methanol,DK0 0 solid biomass,EU methanol,,biomass-to-methanol,0.6100,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 solid biomass biomass-to-methanol,DK1 0 solid biomass,EU methanol,,biomass-to-methanol,0.6100,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 0 methanolisation,DK0 0 H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 methanolisation,DK1 0 H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster methanolization,DK0 cluster H2,EU methanol,,methanolisation,0.8787,True,0,20.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [56]:
n.links.loc[n.links.index.str.contains("Electrolysis")]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 H2 Electrolysis,DK0 0,DK0 0 H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 H2 Electrolysis,DK1 0,DK1 0 H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster H2 Electrolysis,DK0 cluster,DK0 cluster H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [57]:
n.links.loc[n.links["carrier"].str.contains('H2 Electrolysis')]

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 H2 Electrolysis,DK0 0,DK0 0 H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 H2 Electrolysis,DK1 0,DK1 0 H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK0 cluster H2 Electrolysis,DK0 cluster,DK0 cluster H2,,H2 Electrolysis,0.6217,True,0,25.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [58]:
n.buses

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network,country,substation_lv,substation_off
Bus,,,,,,,,,,,,,,,,
DK0 0,380.0,,9.648393,55.893047,AC,MWh_el,DK0 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
DK1 0,380.0,,12.303316,55.515974,AC,MWh_el,DK1 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
EU,1.0,,-5.500000,46.000000,none,,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
co2 atmosphere,1.0,,-5.500000,46.000000,co2,t_co2,EU,1.0,0.0,inf,PQ,,,,NaN,NaN
DK0 0 co2 stored,1.0,,9.648393,55.893047,co2 stored,t_co2,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DK1 0 urban decentral water tanks,1.0,,12.303316,55.515974,urban decentral water tanks,MWh_th,DK1 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 cluster,380.0,,9.648393,55.893047,AC,MWh_el,DK0 0,1.0,0.0,inf,Slack,,,DK,1.0,1.0
DK0 cluster H2,1.0,,9.648393,55.893047,H2,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 cluster storage H2,1.0,,9.648393,55.893047,H2 Store,MWh_LHV,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN
DK0 cluster batteries,1.0,,9.648393,55.893047,battery,MWh_el,DK0 0,1.0,0.0,inf,PQ,,,DK,NaN,NaN

In [59]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,location,unit
Generator,,,,,,,,,,,,,,,,,,,,,
DK0 0 0 offwind-ac,DK0 0,PQ,,1.602600e+03,0.0,True,1602.600000,1.460238e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-ac,DK1 0,PQ,,1.050000e+03,0.0,True,1050.000000,9.543253e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 onwind,DK0 0,PQ,,1.112003e+03,0.0,True,1112.003168,2.885105e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 onwind,DK0 0,PQ,,1.383553e+03,0.0,True,1383.553340,2.095206e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 onwind,DK0 0,PQ,,5.659556e+02,0.0,True,565.955595,7.662129e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 onwind,DK0 0,PQ,,5.978417e+02,0.0,True,597.841651,5.834156e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 onwind,DK1 0,PQ,,1.044400e+02,0.0,True,104.439954,3.679788e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 onwind,DK1 0,PQ,,1.079376e+02,0.0,True,107.937576,2.538478e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 onwind,DK1 0,PQ,,1.375523e+02,0.0,True,137.552329,4.037588e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 onwind,DK1 0,PQ,,2.336286e+02,0.0,True,233.628561,3.824337e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 onwind,DK1 0,PQ,,1.696916e+02,0.0,True,169.691598,1.955588e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 offwind-float,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,6.037907e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-float,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,3.241909e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar-hsat,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,1.057286e+05,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar-hsat,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,3.299191e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 offwind-dc,DK0 0,PQ,,0.000000e+00,0.0,True,0.000000,3.051995e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 offwind-dc,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,9.783270e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar,DK0 0,PQ,,8.002000e+02,0.0,True,800.200000,3.208917e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 solar,DK0 0,PQ,,4.740000e+02,0.0,True,474.000000,4.430542e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 solar,DK0 0,PQ,,2.830000e+02,0.0,True,283.000000,3.151701e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 solar,DK0 0,PQ,,7.350000e+01,0.0,True,73.500000,1.364164e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 4 solar,DK0 0,PQ,,7.000000e+00,0.0,True,7.000000,1.659310e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,4.705808e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 solar,DK1 0,PQ,,1.700000e+02,0.0,True,170.000000,1.841362e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 solar,DK1 0,PQ,,3.540000e+02,0.0,True,354.000000,1.133834e+04,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 solar,DK1 0,PQ,,1.500000e+01,0.0,True,15.000000,2.552206e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 solar,DK1 0,PQ,,0.000000e+00,0.0,True,0.000000,9.716842e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 gas,DK0 0 gas,PQ,,7.803446e+03,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 gas,DK1 0 gas,PQ,,3.379370e+03,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 urban central heat vent,DK0 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK1 0 urban central heat vent,DK1 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK0 0 urban central solar thermal collector,DK0 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 urban central solar thermal collector,DK1 0 urban central heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 biogas,DK0 0 biogas,PQ,,9.364836e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 biogas,DK1 0 biogas,PQ,,2.623672e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 solid biomass,DK0 0 solid biomass,PQ,,9.668602e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 solid biomass,DK1 0 solid biomass,PQ,,2.528983e+06,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 solid biomass transported,DK0 0 solid biomass,PQ,,1.000000e+04,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 solid biomass transported,DK1 0 solid biomass,PQ,,1.000000e+04,0.0,False,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
EU oil primary,EU oil primary,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 0 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.430564e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 1 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.801204e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 2 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.355563e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 3 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,4.278514e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 4 solar rooftop,DK0 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,2.293480e+00,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 0 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,6.137931e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 1 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,1.947568e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 2 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,3.958204e+02,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 3 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,3.186837e+01,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 4 solar rooftop,DK1 0 low voltage,PQ,,0.000000e+00,0.0,True,0.000000,9.587147e+00,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 rural heat vent,DK0 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK0 0 rural solar thermal collector,DK0 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 urban decentral heat vent,DK0 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK0 0,MWh_th
DK0 0 urban decentral solar thermal collector,DK0 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 rural heat vent,DK1 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK1 0 rural solar thermal collector,DK1 0 rural heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK1 0 urban decentral heat vent,DK1 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,-1.0,0.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,DK1 0,MWh_th
DK1 0 urban decentral solar thermal collector,DK1 0 urban decentral heat,PQ,,0.000000e+00,0.0,True,0.000000,inf,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,,
DK0 0 cluster 4 onwind,DK0 cluster,PQ,,0.000000e+00,0.0,True,0.000000,1.229646e+03,0.0,1.0,...,1,0,NaN,NaN,1.0,1.0,1.0,0.0,NaN,NaN

In [60]:
n.links.loc[n.links["carrier"]=='DC']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
relation/5487095-400-DC,DK0 0,DK1 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,False,171.53249
relation/5487095-400-DC-reversed,DK1 0,DK0 0,,DC,0.976096,True,0,inf,600.0,0.0,...,1.0,0.0,relation/5487095,LINESTRING (10.505724427906852 55.365970143543...,1.0,0.560249,NaN,,True,171.53249

In [61]:
n.stores

,bus,type,carrier,e_nom,e_nom_mod,e_nom_extendable,e_nom_min,e_nom_max,e_min_pu,e_max_pu,...,marginal_cost,marginal_cost_quadratic,marginal_cost_storage,capital_cost,standing_loss,active,build_year,lifetime,e_nom_opt,location
Store,,,,,,,,,,,,,,,,,,,,,
co2 atmosphere,co2 atmosphere,,co2,0.000000,0.0,True,0.0,inf,-1.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,True,0,inf,0.0,
DK0 0 co2 stored,DK0 0 co2 stored,,co2 stored,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,247.607546,0.000000,True,0,inf,0.0,
DK1 0 co2 stored,DK1 0 co2 stored,,co2 stored,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,247.607546,0.000000,True,0,inf,0.0,
DK0 0 co2 sequestered,DK0 0 co2 sequestered,,co2 sequestered,0.000000,0.0,True,0.0,7.374268e+08,0.0,1.0,...,-0.1,0.0,0.0,30.000000,0.000000,True,0,50.0,0.0,
DK1 0 co2 sequestered,DK1 0 co2 sequestered,,co2 sequestered,0.000000,0.0,True,0.0,8.677499e+07,0.0,1.0,...,-0.1,0.0,0.0,30.000000,0.000000,True,0,50.0,0.0,
DK0 0 gas Store,DK0 0 gas,,gas,0.000000,0.0,True,3805600.0,inf,0.0,1.0,...,0.0,0.0,0.0,17.851178,0.000000,True,0,inf,0.0,
DK1 0 gas Store,DK1 0 gas,,gas,0.000000,0.0,True,6334336.0,inf,0.0,1.0,...,0.0,0.0,0.0,17.851178,0.000000,True,0,inf,0.0,
DK0 0 H2 Store,DK0 0 H2,,H2 Store,0.000000,0.0,True,0.0,2.013398e+08,0.0,1.0,...,0.0,0.0,0.0,149.047770,0.000000,True,0,100.0,0.0,
DK1 0 H2 Store,DK1 0 H2,,H2 Store,0.000000,0.0,True,0.0,2.879317e+06,0.0,1.0,...,0.0,0.0,0.0,149.047770,0.000000,True,0,100.0,0.0,
DK0 0 battery,DK0 0 battery,,battery,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,12957.628370,0.000000,True,0,25.0,0.0,
DK1 0 battery,DK1 0 battery,,battery,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,12957.628370,0.000000,True,0,25.0,0.0,
DK0 0 EV battery,DK0 0 EV battery,,EV battery,41648.637434,0.0,False,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,True,0,inf,0.0,
DK1 0 EV battery,DK1 0 EV battery,,EV battery,24890.837566,0.0,False,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,True,0,inf,0.0,
DK0 0 urban central water tanks,DK0 0 urban central water tanks,,urban central water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,258.096247,0.000077,True,0,40.0,0.0,
DK1 0 urban central water tanks,DK1 0 urban central water tanks,,urban central water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,258.096247,0.000077,True,0,40.0,0.0,
DK0 0 urban central water pits,DK0 0 urban central water pits,,urban central water pits,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,88.099297,0.000078,True,0,30.0,0.0,
DK1 0 urban central water pits,DK1 0 urban central water pits,,urban central water pits,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,88.099297,0.000078,True,0,30.0,0.0,
EU oil Store,EU oil,,oil,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,2.729244,0.000000,True,0,inf,0.0,
EU NH3 ammonia store,EU NH3,,ammonia store,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,19.083039,0.000000,True,0,20.0,0.0,
EU methanol Store,EU methanol,,methanol,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,5.628412,0.000000,True,0,inf,0.0,
DK0 0 non-sequestered HVC,DK0 0 non-sequestered HVC,,non-sequestered HVC,0.000000,0.0,False,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,True,0,inf,0.0,
DK1 0 non-sequestered HVC,DK1 0 non-sequestered HVC,,non-sequestered HVC,0.000000,0.0,False,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,0.000000,0.000000,True,0,inf,0.0,
DK0 0 home battery,DK0 0 home battery,,home battery,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,18515.043545,0.000000,True,0,25.0,0.0,DK0 0
DK1 0 home battery,DK1 0 home battery,,home battery,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,18515.043545,0.000000,True,0,25.0,0.0,DK1 0
DK0 0 rural water tanks,DK0 0 rural water tanks,,rural water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,28479.294648,0.021000,True,0,30.0,0.0,
DK0 0 urban decentral water tanks,DK0 0 urban decentral water tanks,,urban decentral water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,28479.294648,0.021000,True,0,30.0,0.0,
DK1 0 rural water tanks,DK1 0 rural water tanks,,rural water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,28479.294648,0.021000,True,0,30.0,0.0,
DK1 0 urban decentral water tanks,DK1 0 urban decentral water tanks,,urban decentral water tanks,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,28479.294648,0.021000,True,0,30.0,0.0,
DK0 cluster H2 Store,DK0 cluster storage H2,,H2 Store,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,119.238216,0.000000,True,0,inf,0.0,NaN
DK0 cluster battery Store,DK0 cluster batteries,,battery,0.000000,0.0,True,0.0,inf,0.0,1.0,...,0.0,0.0,0.0,10366.102696,0.000000,True,0,inf,0.0,NaN

In [62]:
n.links.loc[n.links["bus0"]=='EU methanol']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,underground,under_construction,tags,geometry,dc,underwater_fraction,energy to power ratio,location,reversed,length_original
Link,,,,,,,,,,,,,,,,,,,,,
DK0 0 OCGT methanol,EU methanol,DK0 0,,OCGT methanol,0.41,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
DK1 0 OCGT methanol,EU methanol,DK1 0,,OCGT methanol,0.41,True,0,25.0,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
EU industry methanol,EU methanol,EU industry methanol,,industry methanol,1.00,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0
EU shipping methanol,EU methanol,EU shipping methanol,,shipping methanol,1.00,True,0,inf,0.0,0.0,...,NaN,NaN,,,NaN,NaN,NaN,,False,0.0

In [63]:
n.carriers

,co2_emissions,color,nice_name,max_growth,max_relative_growth
Carrier,,,,,
AC,0.0,#70af1d,AC,inf,0.0
DC,0.0,#8a1caf,DC,inf,0.0
offwind-ac,0.0,#6895dd,Offshore Wind (AC),inf,0.0
onwind,0.0,#235ebc,Onshore Wind,inf,0.0
offwind-float,0.0,#b5e2fa,Offshore Wind (Floating),inf,0.0
...,...,...,...,...,...
agriculture machinery electric,0.0,#444578,agriculture machinery electric,inf,0.0
industry electricity,0.0,#2d2a66,industry electricity,inf,0.0
H2 for industry,0.0,#f073da,H2 for industry,inf,0.0
agriculture electricity,0.0,#494778,agriculture electricity,inf,0.0
low-temperature heat for industry,0.0,#8f2727,low-temperature heat for industry,inf,0.0

In [64]:
n.global_constraints

,type,investment_period,carrier_attribute,sense,constant,mu
GlobalConstraint,,,,,,
lv_limit,transmission_volume_expansion_limit,NaN,"AC, DC",<=,1.029195e+05,0.0
biomass limit,operational_limit,NaN,solid biomass,<=,1.219759e+07,0.0
CO2Limit,co2_atmosphere,NaN,co2_emissions,<=,0.000000e+00,0.0

In [65]:
n.loads

,bus,carrier,type,p_set,q_set,sign,active
Load,,,,,,,
DK0 0,DK0 0 low voltage,electricity,,0.000000,0.0,-1.0,True
DK1 0,DK1 0 low voltage,electricity,,0.000000,0.0,-1.0,True
DK0 0 land transport EV,DK0 0 EV battery,land transport EV,,0.000000,0.0,-1.0,True
DK1 0 land transport EV,DK1 0 EV battery,land transport EV,,0.000000,0.0,-1.0,True
DK0 0 urban central heat,DK0 0 urban central heat,urban central heat,,0.000000,0.0,-1.0,True
DK1 0 urban central heat,DK1 0 urban central heat,urban central heat,,0.000000,0.0,-1.0,True
DK0 0 solid biomass for industry,DK0 0 solid biomass for industry,solid biomass for industry,,541.095890,0.0,-1.0,True
DK1 0 solid biomass for industry,DK1 0 solid biomass for industry,solid biomass for industry,,245.433790,0.0,-1.0,True
DK0 0 gas for industry,DK0 0 gas for industry,gas for industry,,155.251142,0.0,-1.0,True
DK1 0 gas for industry,DK1 0 gas for industry,gas for industry,,0.000000,0.0,-1.0,True
DK0 0 H2 for industry,DK0 0 H2,H2 for industry,,0.000000,0.0,-1.0,True
DK1 0 H2 for industry,DK1 0 H2,H2 for industry,,0.000000,0.0,-1.0,True
EU industry methanol,EU industry methanol,industry methanol,,0.000000,0.0,-1.0,True
DK0 0 naphtha for industry,DK0 0 naphtha for industry,naphtha for industry,,0.000000,0.0,-1.0,True
DK1 0 naphtha for industry,DK1 0 naphtha for industry,naphtha for industry,,0.000000,0.0,-1.0,True
DK0 0 low-temperature heat for industry,DK0 0 urban central heat,low-temperature heat for industry,,52.511416,0.0,-1.0,True
DK1 0 low-temperature heat for industry,DK1 0 urban central heat,low-temperature heat for industry,,15.981735,0.0,-1.0,True
DK0 0 industry electricity,DK0 0 low voltage,industry electricity,,1545.662100,0.0,-1.0,True
DK1 0 industry electricity,DK1 0 low voltage,industry electricity,,426.940639,0.0,-1.0,True
DK0 0 process emissions,DK0 0 process emissions,process emissions,,-172.374429,0.0,-1.0,True
DK1 0 process emissions,DK1 0 process emissions,process emissions,,-2.283105,0.0,-1.0,True
EU NH3,EU NH3,NH3,,0.000000,0.0,-1.0,True
EU shipping methanol,EU shipping methanol,shipping methanol,,994.774763,0.0,-1.0,True
DK0 0 kerosene for aviation,DK0 0 kerosene for aviation,kerosene for aviation,,895.233382,0.0,-1.0,True
DK1 0 kerosene for aviation,DK1 0 kerosene for aviation,kerosene for aviation,,535.026115,0.0,-1.0,True
DK0 0 agriculture electricity,DK0 0 low voltage,agriculture electricity,,79.508120,0.0,-1.0,True
DK1 0 agriculture electricity,DK1 0 low voltage,agriculture electricity,,47.517130,0.0,-1.0,True
DK0 0 agriculture heat,DK0 0 rural heat,agriculture heat,,337.963851,0.0,-1.0,True
DK1 0 agriculture heat,DK1 0 rural heat,agriculture heat,,201.980277,0.0,-1.0,True
DK0 0 agriculture machinery electric,DK0 0 low voltage,agriculture machinery electric,,38.233166,0.0,-1.0,True
DK1 0 agriculture machinery electric,DK1 0 low voltage,agriculture machinery electric,,22.849619,0.0,-1.0,True
DK0 0 agriculture machinery oil,DK0 0 agriculture machinery oil,agriculture machinery oil,,89.210720,0.0,-1.0,True
DK1 0 agriculture machinery oil,DK1 0 agriculture machinery oil,agriculture machinery oil,,53.315779,0.0,-1.0,True
DK0 0 rural heat,DK0 0 rural heat,rural heat,,0.000000,0.0,-1.0,True
DK0 0 urban decentral heat,DK0 0 urban decentral heat,urban decentral heat,,0.000000,0.0,-1.0,True
DK1 0 rural heat,DK1 0 rural heat,rural heat,,0.000000,0.0,-1.0,True
DK1 0 urban decentral heat,DK1 0 urban decentral heat,urban decentral heat,,0.000000,0.0,-1.0,True

**Exporting**

In [66]:
n.export_to_netcdf(fn)

INFO:pypsa.network.io:Exported network 'Unnamed Network'saved to 'resources/DK_test/networks/base_s_2__12h_2050.nc contains: carriers, loads, generators, stores, global_constraints, buses, links

<xarray.Dataset> Size: 504kB
Dimensions:                               (snapshots: 730,
                                           investment_periods: 0,
                                           carriers_i: 118, loads_i: 37,
                                           loads_t_p_set_i: 10,
                                           generators_i: 59,
                                           generators_t_p_max_pu_i: 44,
                                           ...
                                           stores_t_e_min_pu_i: 2,
                                           stores_t_e_max_pu_i: 4,
                                           global_constraints_i: 3,
                                           buses_i: 62, links_i: 143,
                                           links_t_efficiency_i: 8,
                                           links_t_p_max_pu_i: 4)
Coordinates: (12/15)
  * snapshots                             (snapshots) int64 6kB 0 1 ... 728 729
  * investment_periods                    (investment_periods) object 0B
  * carriers_i                            (carriers_i) object 944B 'AC' ... '...
  * loads_i                               (loads_i) object 296B 'DK0 0' ... '...
  * loads_t_p_set_i                       (loads_t_p_set_i) object 80B 'DK0 0...
  * generators_i                          (generators_i) object 472B 'DK0 0 0...
    ...                                    ...
  * stores_t_e_max_pu_i                   (stores_t_e_max_pu_i) object 32B 'D...
  * global_constraints_i                  (global_constraints_i) object 24B '...
  * buses_i                               (buses_i) object 496B 'DK0 0' ... '...
  * links_i                               (links_i) object 1kB 'relation/5487...
  * links_t_efficiency_i                  (links_t_efficiency_i) object 64B '...
  * links_t_p_max_pu_i                    (links_t_p_max_pu_i) object 32B 'DK...
Data variables: (12/90)
    snapshots_snapshot                    (snapshots) datetime64[ns] 6kB 2013...
    snapshots_objective                   (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_stores                      (snapshots) float64 6kB 12.0 ... 12.0
    snapshots_generators                  (snapshots) float64 6kB 12.0 ... 12.0
    investment_periods_objective          (investment_periods) float64 0B
    investment_periods_years              (investment_periods) float64 0B
    ...                                    ...
    links_energy to power ratio           (links_i) float64 1kB nan nan ... nan
    links_location                        (links_i) object 1kB '' '' ... nan nan
    links_reversed                        (links_i) bool 143B False ... True
    links_length_original                 (links_i) float64 1kB 171.5 ... nan
    links_t_efficiency                    (snapshots, links_t_efficiency_i) float64 47kB ...
    links_t_p_max_pu                      (snapshots, links_t_p_max_pu_i) float64 23kB ...
Attributes:
    network__multi_invest:  0
    network_name:           Unnamed Network
    network_pypsa_version:  0.35.2
    network_srid:           4326
    crs:                    {"_crs": "GEOGCRS[\"WGS 84\",ENSEMBLE[\"World Geo...
    meta:                   {"version": "v2025.07.0", "tutorial": false, "log...